### PR TITLE
Hyperlinks are rendered properly

### LINKED ISSUE #92: Implicit links not working.
Any course content which is of a ‘link type’.  Say course EEE F245 has experiment 1 as one of the topics. The topic is not hyperlinked to the content. It’s just plain text.

### PR DESCRIPTION
**Pull request by abhijeetviswa**
Hyperlinks in CoureSections and Discussions weren't being rendered properly

CourseSection descriptions are HTML strings with anchor tags to mark links.
However, insertion of the "Show More" span removes the URLSpan created from
the original HTML string by converting the spanned string to a plain string.
This commit ensures that the "Show More" span is added along with the URLSpan
instead of overwriting the URLSpan.

Discussions didn't have support for hyperlinks

Close #92

### CODE REVIEW

File: app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java [hunk 1]
```diff
@@ -318,46 +315,67 @@ private String addToken(String descriptionWithOutExtraSpace) {
...
+                        /* Find out how much is actually visible (without HTML tags) and grab the HTML description till that part */
+                        if (descriptionText.length() > lineEndIndex) {
+
+                            /* Start from lineEndIndex and find out the next complete word */
+                            String nearestWord = Util.nextNearestWord(descriptionText, lineEndIndex);
+                            displayText = descriptionHtml.subSequence(0, descriptionHtml.indexOf(nearestWord)).toString() + "\n" + expandText;
+
+                        }else displayText = descriptionHtml;
+                    } else if (description.getLineCount() <= maxLine) {
+                        displayText = descriptionText;
```
Comment (TheGamer007) [inline app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java]: I suppose it should be `descriptionHtml` instead of `descriptionText` here?

File: app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java [hunk 2]
```diff
@@ -318,46 +315,67 @@ private String addToken(String descriptionWithOutExtraSpace) {
...
+                    } else {
```
Comment (TheGamer007) [inline app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java]: Under what conditions is this `else` block triggered? Aren't the previous 3 conditions exhaustive?

File: app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java [hunk 3]
```diff
@@ -318,46 +315,67 @@ private String addToken(String descriptionWithOutExtraSpace) {
...
+                        int lineEndIndex = description.getLayout().getLineEnd(description.getLayout().getLineCount() - 1);
+                        /* Find out how much is actually visible (without HTML tags) and grab the HTML description till that part */
+                        if (descriptionText.length() > lineEndIndex)
+                            displayText = descriptionHtml.subSequence(0, descriptionHtml.indexOf(descriptionText.subSequence(lineEndIndex - 5, lineEndIndex).toString()) + 5) + "\n" + expandText;
```
Comment (TheGamer007) [inline app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java]: Can you explain this? Avoid using fixed numbers (`5`, in this case) without a comment to explain how that was arrived upon.

File: app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java (hunk 1 above)
Comment (abhijeetviswa) [reply app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java]: Yes. This should be decriptionHtml instead of decriptionText.

File: app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java [hunk 4]
```diff
@@ -259,17 +260,22 @@ public void onClick(View view) {
                 getActivity().overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left);
             }
         });*/
+        section.setSummary("Dear Student,<br /><br />As per Prof. YVD Rao's request, I agreed to exchange F103 with F208. <br /><br />So students who were previously assigned F103 are moved F208, F102 and F105. Please go through the <a href=\"https://docs.google.com/spreadsheets/d/1NoVh3kw7UyKHL4Y407EY_SFJZ9oprglHO_cqbYnlF5U/edit?usp=sharing\"><b>Google Spreadsheet</b></a> to see the changes.<br /><br />Sorry for the last minute change.<br /><br />Best<br />Santosh<br />");
```
Comment (TheGamer007) [inline app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java]: You missed this, which seems to be hardcoded for testing purposes.

Comment (abhijeetviswa) [reply app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java]: Noob mistake. Thank God this was caught.
